### PR TITLE
counters

### LINKED ISSUE #2342: eId re-writing generates many mutations in provision editor and large provisions crash
e.g. https://indigo.kenyalaw.org/documents/10873/att_6
https://www.loom.com/share/8d605d14b7844b79ad64adc9e4f81643

### PR DESCRIPTION
**Pull request by goose-life**
partially closes #2342

### CODE REVIEW

File: indigo_app/static/javascript/indigo/models.js [hunk 1]
```diff
@@ -135,7 +135,8 @@
       if (Indigo.Preloads.provisionEid && Indigo.Preloads.provisionEid.lastIndexOf('__') > -1) {
         eidPrefix = Indigo.Preloads.provisionEid.substring(0, Indigo.Preloads.provisionEid.lastIndexOf('__'));
       }
-      new indigoAkn.EidRewriter().rewriteAllEids(this.xmlDocument.documentElement, eidPrefix);
+      new indigoAkn.EidRewriter(Indigo.Preloads.provisionCounters, Indigo.Preloads.eidCounter)
```
Comment (longhotsummer) [inline indigo_app/static/javascript/indigo/models.js:138]: You can forego all changes to EidRewriter by doing something like:

```js
rewriter = new indigoAkn.EidRewriter();
rewriter.counters = Indigo.Preloads...
rewriter.eidCounter = Indigo.Preloads...
rewrite.rewriteEid(this.xmlDocument.documentElement, eidPrefix);
```

Comment (goose-life) [reply indigo_app/static/javascript/indigo/models.js:138]: woah! I can!

File: indigo_app/views/documents.py [hunk 2]
```diff
@@ -139,11 +138,41 @@ def get(self, request, *args, **kwargs):
...
         context = super().get_context_data(**kwargs)
         context['provision_eid'] = self.eid
+        context['provision_counters'], context['eid_counter'] = self.get_counters()
         return context
 
     def get_document_content_json(self, document):
         return json.dumps(etree.tostring(self.provision_xml, encoding='unicode'))
 
+    def get_counters(self):
+        """ Generate provision and eid counters based on the content preceding our element.
```
Comment (longhotsummer) [inline indigo_app/views/documents.py:148]: nice - as I understand it, you're chopping off everything after this element in the tree. So we'll generate eIds for everything up to it (excluding it).

File: indigo_app/views/documents.py [hunk 3]
```diff
@@ -139,11 +138,41 @@ def get(self, request, *args, **kwargs):
...
+        generator = XmlGenerator(self.object.frbr_uri)
+        generator.generate_eids(root)
+        return json.dumps(generator.ids.counters), json.dumps(generator.ids.eid_counter)
+
+    def nuke_following(self, element):
+        parent = element.getparent()
+        if parent is not None:
+            for sibling in parent.itersiblings():
+                sibling.getparent().remove(sibling)
+            self.nuke_following(parent)
```
Comment (longhotsummer) [inline indigo_app/views/documents.py:174]:
```suggestion
    def nuke_following(self, element):
        parent = element.getparent()
        while parent is not None:
            for sibling in parent.itersiblings():
                sibling.getparent().remove(sibling)
            parent = parent.getparent()
```

a loop is better than recursion

File: indigo_app/views/documents.py [hunk 4]
```diff
@@ -139,11 +138,41 @@ def get(self, request, *args, **kwargs):
...
 
+    def get_counters(self):
+        """ Generate provision and eid counters based on the content preceding our element.
+            This way we don't end up 'correcting' e.g. part_II_2 to part_II,
+             because the context will now be aware of the preceding part_II that isn't being edited.
+        """
+        root = etree.fromstring(self.object.document_xml)
+        element = root.xpath(f'.//a:*[@eId="{self.eid}"]', namespaces={'a': self.object.doc.namespace})[0]
+        parent = element.getparent()
+        # remove everything from (and including) our element from the tree
```
Comment (longhotsummer) [inline indigo_app/views/documents.py:155]:
```suggestion
        # remove everything from our element onwards (inclusive) from the tree
```

File: indigo_app/static/javascript/indigo/models.js [hunk 5]
```diff
@@ -135,7 +135,8 @@
...
+        .rewriteAllEids(this.xmlDocument.documentElement, eidPrefix);
       // rewrite all attachment FRBR URI work components too
       new indigoAkn.WorkComponentRewriter().rewriteAllAttachmentWorkComponents(this.xmlDocument.documentElement);
```
Comment (longhotsummer) [inline indigo_app/static/javascript/indigo/models.js:141]: Do we need to do something similar to this rewriter?

File: indigo_app/views/documents.py (hunk 2 above)
Comment (goose-life) [reply indigo_app/views/documents.py:148]: exactly, yes, which is what the rewriter uses when calculating an eid / checking it for uniqueness

File: indigo_app/static/javascript/indigo/models.js (hunk 5 above)
Comment (goose-life) [reply indigo_app/static/javascript/indigo/models.js:146]: I believe so, yes — looking into that next 🙏

**Comment by longhotsummer** [comment]
looks good.

**Review by longhotsummer — DISMISSED** [review]
